In [ ]:
# ============================================================
# Global Satellite Intelligence Platform (GSIP)
# Notebook: 01_Data_Understanding.ipynb
# Author: Priyal Rathore
# Description:
# Initial exploration and understanding of the
# UCS Satellite Database.
# ============================================================

In [1]:
import pandas as pd
import numpy as np

In [2]:
file_path = "../data/raw/UCS-Satellite-Database 5-1-2023.xlsx"

In [1]:
import pandas as pd

excel_file = pd.ExcelFile(r"C:\Global-Satellite-Intelligence-Platform\data\raw\UCS-Satellite-Database 5-1-2023.xlsx")

print("Worksheets:")
print(excel_file.sheet_names)

Worksheets:
['Sheet1', 'Sheet2', 'Sheet3']

In [3]:
# Read the first worksheet containing the satellite data
df = pd.read_excel(excel_file, sheet_name="Sheet1")

In [4]:
df.head()

,"Name of Satellite, Alternate Names",Current Official Name of Satellite,Country/Org of UN Registry,Country of Operator/Owner,Operator/Owner,Users,Purpose,Detailed Purpose,Class of Orbit,Type of Orbit,...,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67
0,1HOPSAT-TD (1st-generation High Optical Perfor...,1HOPSAT-TD,NR,USA,Hera Systems,Commercial,Earth Observation,Infrared Imaging,LEO,Non-Polar Inclined,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AAC AIS-Sat1 (Kelpie 1),AAC AIS-Sat1 (Kelpie 1),United Kingdom,United Kingdom,AAC Clyde Space,Commercial,Earth Observation,Automatic Identification System (AIS),LEO,Sun-Synchronous,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aalto-1,Aalto-1,Finland,Finland,Aalto University,Civil,Technology Development,NaN,LEO,Sun-Synchronous,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AAt-4,AAt-4,Denmark,Denmark,University of Aalborg,Civil,Earth Observation,Automatic Identification System (AIS),LEO,Sun-Synchronous,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"ABS-2 (Koreasat-8, ST-3)",ABS-2,NR,Multinational,Asia Broadcast Satellite Ltd.,Commercial,Communications,NaN,GEO,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.tail()

,"Name of Satellite, Alternate Names",Current Official Name of Satellite,Country/Org of UN Registry,Country of Operator/Owner,Operator/Owner,Users,Purpose,Detailed Purpose,Class of Orbit,Type of Orbit,...,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67
7555,Ziyuan 1-02C,Ziyuan 1-02C,China,China,China Centre for Resources Satellite Data and ...,Government,Earth Observation,Optical Imaging,LEO,Sun-Synchronous,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7556,Ziyuan 1-2D,Ziyuan 1-2D,NR,China,China Centre for Resources Satellite Data and ...,Government,Earth Observation,Hyperspectral Imaging,LEO,Sun-Synchronous,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7557,Ziyuan 3 (ZY-3),Ziyuan 3,China,China,China Centre for Resources Satellite Data and ...,Government,Earth Observation,Optical Imaging,LEO,Sun-Synchronous,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7558,Ziyuan 3-2,Ziyuan 3-2,China,China,China Centre for Resources Satellite Data and ...,Government,Earth Observation,Optical Imaging,LEO,Sun-Synchronous,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7559,Ziyuan 3-3,Ziyuan 3-3,China,China,China Centre for Resources Satellite Data and ...,Government,Earth Observation,Optical Imaging,LEO,Sun-Synchronous,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
print("=" * 40)
print("DATASET DIMENSIONS")
print("=" * 40)

rows, columns = df.shape

print(f"Number of Rows    : {rows}")
print(f"Number of Columns : {columns}")

========================================
DATASET DIMENSIONS
========================================
Number of Rows    : 7560
Number of Columns : 68

In [7]:
print("=" * 40)
print("COLUMN NAMES")
print("=" * 40)

for index, column in enumerate(df.columns, start=1):
    print(f"{index}. {column}")

========================================
COLUMN NAMES
========================================
1. Name of Satellite, Alternate Names
2. Current Official Name of Satellite
3. Country/Org of UN Registry
4. Country of Operator/Owner
5. Operator/Owner
6. Users
7. Purpose
8. Detailed Purpose
9. Class of Orbit
10. Type of Orbit
11. Longitude of GEO (degrees)
12. Perigee (km)
13. Apogee (km)
14. Eccentricity
15. Inclination (degrees)
16. Period (minutes)
17. Launch Mass (kg.)
18. Dry Mass (kg.)
19. Power (watts)
20. Date of Launch
21. Expected Lifetime (yrs.)
22. Contractor
23. Country of Contractor
24. Launch Site
25. Launch Vehicle
26. COSPAR Number
27. NORAD Number
28. Comments
29. Unnamed: 28
30. Source Used for Orbital Data
31. Source
32. Source.1
33. Source.2
34. Source.3
35. Source.4
36. Source.5
37. Source.6
38. Unnamed: 37
39. Unnamed: 38
40. Unnamed: 39
41. Unnamed: 40
42. Unnamed: 41
43. Unnamed: 42
44. Unnamed: 43
45. Unnamed: 44
46. Unnamed: 45
47. Unnamed: 46
48. Unnamed: 47
49. Unnamed: 48
50. Unnamed: 49
51. Unnamed: 50
52. Unnamed: 51
53. Unnamed: 52
54. Unnamed: 53
55. Unnamed: 54
56. Unnamed: 55
57. Unnamed: 56
58. Unnamed: 57
59. Unnamed: 58
60. Unnamed: 59
61. Unnamed: 60
62. Unnamed: 61
63. Unnamed: 62
64. Unnamed: 63
65. Unnamed: 64
66. Unnamed: 65
67. Unnamed: 66
68. Unnamed: 67

In [8]:
print("=" * 40)
print("DATA TYPES")
print("=" * 40)

df.dtypes

========================================
DATA TYPES
========================================

Name of Satellite, Alternate Names    object
Current Official Name of Satellite    object
Country/Org of UN Registry            object
Country of Operator/Owner             object
Operator/Owner                        object
                                       ...
Unnamed: 63                           object
Unnamed: 64                           object
Unnamed: 65                           object
Unnamed: 66                           object
Unnamed: 67                           object
Length: 68, dtype: object

In [9]:
print("=" * 40)
print("DATASET INFORMATION")
print("=" * 40)

df.info()

========================================
DATASET INFORMATION
========================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7560 entries, 0 to 7559
Data columns (total 68 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Name of Satellite, Alternate Names  7560 non-null   object
 1   Current Official Name of Satellite  7560 non-null   object
 2   Country/Org of UN Registry          7559 non-null   object
 3   Country of Operator/Owner           7560 non-null   object
 4   Operator/Owner                      7560 non-null   object
 5   Users                               7560 non-null   object
 6   Purpose                             7560 non-null   object
 7   Detailed Purpose                    1254 non-null   object
 8   Class of Orbit                      7560 non-null   object
 9   Type of Orbit                       6909 non-null   object
 10  Longitude of GEO (degrees)          7557 non-null   float64
 11  Perigee (km)                        7553 non-null   float64
 12  Apogee (km)                         7553 non-null   float64
 13  Eccentricity                        7549 non-null   float64
 14  Inclination (degrees)               7556 non-null   float64
 15  Period (minutes)                    7504 non-null   float64
 16  Launch Mass (kg.)                   7315 non-null   float64
 17  Dry Mass (kg.)                      767 non-null    object
 18  Power (watts)                       579 non-null    object
 19  Date of Launch                      7559 non-null   object
 20  Expected Lifetime (yrs.)            5450 non-null   float64
 21  Contractor                          7560 non-null   object
 22  Country of Contractor               7560 non-null   object
 23  Launch Site                         7560 non-null   object
 24  Launch Vehicle                      7560 non-null   object
 25  COSPAR Number                       7560 non-null   object
 26  NORAD Number                        7560 non-null   int64
 27  Comments                            2085 non-null   object
 28  Unnamed: 28                         5 non-null      object
 29  Source Used for Orbital Data        6636 non-null   object
 30  Source                              3286 non-null   object
 31  Source.1                            725 non-null    object
 32  Source.2                            1832 non-null   object
 33  Source.3                            1126 non-null   object
 34  Source.4                            729 non-null    object
 35  Source.5                            553 non-null    object
 36  Source.6                            504 non-null    object
 37  Unnamed: 37                         484 non-null    object
 38  Unnamed: 38                         484 non-null    object
 39  Unnamed: 39                         484 non-null    object
 40  Unnamed: 40                         484 non-null    object
 41  Unnamed: 41                         484 non-null    object
 42  Unnamed: 42                         484 non-null    object
 43  Unnamed: 43                         484 non-null    object
 44  Unnamed: 44                         484 non-null    object
 45  Unnamed: 45                         484 non-null    object
 46  Unnamed: 46                         484 non-null    object
 47  Unnamed: 47                         484 non-null    object
 48  Unnamed: 48                         484 non-null    object
 49  Unnamed: 49                         484 non-null    object
 50  Unnamed: 50                         484 non-null    object
 51  Unnamed: 51                         484 non-null    object
 52  Unnamed: 52                         484 non-null    object
 53  Unnamed: 53                         485 non-null    object
 54  Unnamed: 54                         485 non-null    object
 55  Unnamed: 55                         485 non-null    object
 56  Unnamed: 56                         485 non-null    object
 57  Unnamed: 57                         485 non-null    object
 58  Unnamed: 58                         485 non-null    object
 59  Unnamed: 59                         485 non-null    object
 60  Unnamed: 60                         488 non-null    object
 61  Unnamed: 61                         488 non-null    object
 62  Unnamed: 62                         487 non-null    object
 63  Unnamed: 63                         485 non-null    object
 64  Unnamed: 64                         485 non-null    object
 65  Unnamed: 65                         485 non-null    object
 66  Unnamed: 66                         487 non-null    object
 67  Unnamed: 67                         485 non-null    object
dtypes: float64(8), int64(1), object(59)
memory usage: 3.9+ MB

In [10]:
df.describe()

,Longitude of GEO (degrees),Perigee (km),Apogee (km),Eccentricity,Inclination (degrees),Period (minutes),Launch Mass (kg.),Expected Lifetime (yrs.),NORAD Number
count,7557.000000,7553.000000,7553.000000,7549.000000,7556.000000,7504.000000,7315.000000,5450.000000,7560.000000
mean,1.704567,3703.945187,4236.369390,0.480882,62.534161,224.016189,626.321319,5.350413,47911.917857
std,26.292065,9715.789212,13123.003517,15.567178,27.236581,441.495461,1386.207982,3.421953,6559.550969
min,-179.800000,150.000000,49.000000,-0.033429,0.000000,9.000000,0.500000,0.250000,7530.000000
25%,0.000000,521.000000,536.000000,0.000199,53.000000,95.000000,148.000000,4.000000,44905.750000
50%,0.000000,548.000000,561.000000,0.000297,53.200000,95.600000,260.000000,4.000000,48448.500000
75%,0.000000,600.000000,626.000000,0.000939,87.400000,96.500000,280.000000,5.000000,53091.000000
max,359.000000,62200.000000,353798.000000,575.000000,143.400000,11520.000000,22500.000000,30.000000,62684.000000

In [11]:
df.describe(include="all")

,"Name of Satellite, Alternate Names",Current Official Name of Satellite,Country/Org of UN Registry,Country of Operator/Owner,Operator/Owner,Users,Purpose,Detailed Purpose,Class of Orbit,Type of Orbit,...,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67
count,7560,7560,7559,7560,7560,7560,7560,1254,7560,6909,...,485,485,488,488,487,485,485,485,487,485
unique,7543,7530,69,105,668,20,31,54,5,10,...,1,1,3,3,2,1,1,1,2,1
top,SB-WASS 3-5 (Space Based Wide Area Surveillanc...,Jilin-1,USA,USA,SpaceX,Commercial,Communications,Optical Imaging,LEO,Non-Polar Inclined,...,Estimated,Estimated,Estimated,Estimated,Estimated,Estimated,Estimated,Estimated,Estimated,Estimated
freq,2,5,4991,5165,3950,6080,5514,516,6767,4042,...,485,485,485,485,485,485,485,485,485,485
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

1. Name of Satellite, Alternate Names
2. Current Official Name of Satellite
3. Country/Org of UN Registry
4. Country of Operator/Owner
5. Operator/Owner
6. Users
7. Purpose
8. Detailed Purpose
9. Class of Orbit
10. Type of Orbit
11. Longitude of GEO (degrees)
12. Perigee (km)
13. Apogee (km)
14. Eccentricity
15. Inclination (degrees)
16. Period (minutes)
17. Launch Mass (kg.)
18. Dry Mass (kg.)
19. Power (watts)
20. Date of Launch
21. Expected Lifetime (yrs.)
22. Contractor
23. Country of Contractor
24. Launch Site
25. Launch Vehicle
26. COSPAR Number
27. NORAD Number
28. Comments
29. Unnamed: 28
30. Source Used for Orbital Data
31. Source
32. Source.1
33. Source.2
34. Source.3
35. Source.4
36. Source.5
37. Source.6
38. Unnamed: 37
39. Unnamed: 38
40. Unnamed: 39
41. Unnamed: 40
42. Unnamed: 41
43. Unnamed: 42
44. Unnamed: 43
45. Unnamed: 44
46. Unnamed: 45
47. Unnamed: 46
48. Unnamed: 47
49. Unnamed: 48
50. Unnamed: 49
51. Unnamed: 50
52. Unnamed: 51
53. Unnamed: 52
54. Unnamed: 53
55. Unnamed: 54
56. Unnamed: 55
57. Unnamed: 56
58. Unnamed: 57
59. Unnamed: 58
60. Unnamed: 59
61. Unnamed: 60
62. Unnamed: 61
63. Unnamed: 62
64. Unnamed: 63
65. Unnamed: 64
66. Unnamed: 65
67. Unnamed: 66
68. Unnamed: 67

In [16]:
# Create a DataFrame of all column names
columns_df = pd.DataFrame({
    "Column Number": range(1, len(df.columns) + 1),
    "Column Name": df.columns
})

columns_df

    Column Number                         Column Name
0               1  Name of Satellite, Alternate Names
1               2  Current Official Name of Satellite
2               3          Country/Org of UN Registry
3               4           Country of Operator/Owner
4               5                      Operator/Owner
..            ...                                 ...
63             64                         Unnamed: 63
64             65                         Unnamed: 64
65             66                         Unnamed: 65
66             67                         Unnamed: 66
67             68                         Unnamed: 67

[68 rows x 2 columns]

In [17]:
columns_df.to_csv("../docs/column_names.csv", index=False)

print("Column names exported successfully!")

Column names exported successfully!

In [18]:
print("=" * 50)
print("DATASET SHAPE")
print("=" * 50)

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

==================================================
DATASET SHAPE
==================================================
Rows    : 7560
Columns : 68

In [19]:
print("=" * 50)
print("MISSING VALUES")
print("=" * 50)

missing_values = df.isnull().sum()

missing_df = pd.DataFrame({
    "Column": df.columns,
    "Missing Values": missing_values,
    "Missing Percentage": round((missing_values / len(df)) * 100, 2)
})

missing_df = missing_df.sort_values(
    by="Missing Values",
    ascending=False
)

missing_df

==================================================
MISSING VALUES
==================================================

                      Column  Missing Values  Missing Percentage
Unnamed: 28      Unnamed: 28            7555               99.93
Unnamed: 50      Unnamed: 50            7076               93.60
Unnamed: 51      Unnamed: 51            7076               93.60
Unnamed: 49      Unnamed: 49            7076               93.60
Unnamed: 52      Unnamed: 52            7076               93.60
...                      ...             ...                 ...
Contractor        Contractor               0                0.00
COSPAR Number  COSPAR Number               0                0.00
NORAD Number    NORAD Number               0                0.00
Users                  Users               0                0.00
Purpose              Purpose               0                0.00

[68 rows x 3 columns]

In [20]:
print("=" * 50)
print("DUPLICATE RECORDS")
print("=" * 50)

duplicates = df.duplicated().sum()

print(f"Duplicate Rows: {duplicates}")

==================================================
DUPLICATE RECORDS
==================================================
Duplicate Rows: 7

In [21]:
unique_df = pd.DataFrame({
    "Column": df.columns,
    "Unique Values": df.nunique()
})

unique_df

,Column,Unique Values
"Name of Satellite, Alternate Names","Name of Satellite, Alternate Names",7543
Current Official Name of Satellite,Current Official Name of Satellite,7530
Country/Org of UN Registry,Country/Org of UN Registry,69
Country of Operator/Owner,Country of Operator/Owner,105
Operator/Owner,Operator/Owner,668
...,...,...
Unnamed: 63,Unnamed: 63,1
Unnamed: 64,Unnamed: 64,1
Unnamed: 65,Unnamed: 65,1
Unnamed: 66,Unnamed: 66,2
Unnamed: 67,Unnamed: 67,1

In [22]:
dtype_summary = df.dtypes.value_counts()

print(dtype_summary)

object     59
float64     8
int64       1
Name: count, dtype: int64

In [23]:
memory = df.memory_usage(deep=True).sum() / (1024 ** 2)

print(f"Memory Usage: {memory:.2f} MB")

Memory Usage: 19.58 MB

In [24]:
numeric_summary = df.describe()

numeric_summary

,Longitude of GEO (degrees),Perigee (km),Apogee (km),Eccentricity,Inclination (degrees),Period (minutes),Launch Mass (kg.),Expected Lifetime (yrs.),NORAD Number
count,7557.000000,7553.000000,7553.000000,7549.000000,7556.000000,7504.000000,7315.000000,5450.000000,7560.000000
mean,1.704567,3703.945187,4236.369390,0.480882,62.534161,224.016189,626.321319,5.350413,47911.917857
std,26.292065,9715.789212,13123.003517,15.567178,27.236581,441.495461,1386.207982,3.421953,6559.550969
min,-179.800000,150.000000,49.000000,-0.033429,0.000000,9.000000,0.500000,0.250000,7530.000000
25%,0.000000,521.000000,536.000000,0.000199,53.000000,95.000000,148.000000,4.000000,44905.750000
50%,0.000000,548.000000,561.000000,0.000297,53.200000,95.600000,260.000000,4.000000,48448.500000
75%,0.000000,600.000000,626.000000,0.000939,87.400000,96.500000,280.000000,5.000000,53091.000000
max,359.000000,62200.000000,353798.000000,575.000000,143.400000,11520.000000,22500.000000,30.000000,62684.000000

In [25]:
categorical_summary = df.describe(include="object")

categorical_summary

,"Name of Satellite, Alternate Names",Current Official Name of Satellite,Country/Org of UN Registry,Country of Operator/Owner,Operator/Owner,Users,Purpose,Detailed Purpose,Class of Orbit,Type of Orbit,...,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67
count,7560,7560,7559,7560,7560,7560,7560,1254,7560,6909,...,485,485,488,488,487,485,485,485,487,485
unique,7543,7530,69,105,668,20,31,54,5,10,...,1,1,3,3,2,1,1,1,2,1
top,SB-WASS 3-5 (Space Based Wide Area Surveillanc...,Jilin-1,USA,USA,SpaceX,Commercial,Communications,Optical Imaging,LEO,Non-Polar Inclined,...,Estimated,Estimated,Estimated,Estimated,Estimated,Estimated,Estimated,Estimated,Estimated,Estimated
freq,2,5,4991,5165,3950,6080,5514,516,6767,4042,...,485,485,485,485,485,485,485,485,485,485

In [26]:
missing_df.to_csv(
    "../reports/data_profile_summary.csv",
    index=False
)

print("Data profile report saved successfully.")

Data profile report saved successfully.

In [27]:
missing_df.head(20)

                  Column  Missing Values  Missing Percentage
Unnamed: 28  Unnamed: 28            7555               99.93
Unnamed: 50  Unnamed: 50            7076               93.60
Unnamed: 51  Unnamed: 51            7076               93.60
Unnamed: 49  Unnamed: 49            7076               93.60
Unnamed: 52  Unnamed: 52            7076               93.60
Unnamed: 43  Unnamed: 43            7076               93.60
Unnamed: 41  Unnamed: 41            7076               93.60
Unnamed: 42  Unnamed: 42            7076               93.60
Unnamed: 47  Unnamed: 47            7076               93.60
Unnamed: 46  Unnamed: 46            7076               93.60
Unnamed: 45  Unnamed: 45            7076               93.60
Unnamed: 48  Unnamed: 48            7076               93.60
Unnamed: 44  Unnamed: 44            7076               93.60
Unnamed: 39  Unnamed: 39            7076               93.60
Unnamed: 38  Unnamed: 38            7076               93.60
Unnamed: 37  Unnamed: 37            7076               93.60
Unnamed: 40  Unnamed: 40            7076               93.60
Unnamed: 58  Unnamed: 58            7075               93.58
Unnamed: 57  Unnamed: 57            7075               93.58
Unnamed: 56  Unnamed: 56            7075               93.58

In [28]:
dtype_summary

object     59
float64     8
int64       1
Name: count, dtype: int64