In [4]:
# Global Satellite Intelligence Platform (GSIP)

## Notebook: 02_Data_Cleaning.ipynb

### Objective

This notebook performs preprocessing and cleaning of the Union of Concerned Scientists (UCS) Satellite Database.

The cleaned dataset will be used for SQL analysis, exploratory data analysis (EDA), and Power BI dashboard development.

The original raw dataset remains unchanged throughout this process.

SyntaxError: invalid syntax (3966241660.py, line 7)

In [5]:
import pandas as pd
import numpy as np

In [6]:
excel_file = pd.ExcelFile(
    r"C:\Global-Satellite-Intelligence-Platform\data\raw\UCS-Satellite-Database 5-1-2023.xlsx"
)

df = pd.read_excel(excel_file, sheet_name="Sheet1")

In [7]:
# Create a copy of the original dataset
clean_df = df.copy()

print("Working copy created successfully.")

Working copy created successfully.

In [8]:
print("=" * 50)
print("INITIAL DATASET")
print("=" * 50)

print(f"Rows    : {clean_df.shape[0]}")
print(f"Columns : {clean_df.shape[1]}")

==================================================
INITIAL DATASET
==================================================
Rows    : 7560
Columns : 68

In [9]:
duplicates = clean_df.duplicated().sum()

print(f"Duplicate Rows Found: {duplicates}")

Duplicate Rows Found: 7

In [10]:
duplicate_rows = clean_df[clean_df.duplicated()]

duplicate_rows

,"Name of Satellite, Alternate Names",Current Official Name of Satellite,Country/Org of UN Registry,Country of Operator/Owner,Operator/Owner,Users,Purpose,Detailed Purpose,Class of Orbit,Type of Orbit,...,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67
6204,Starlink-5016,Starlink-5016,USA,USA,SpaceX,Commercial,Communications,NaN,LEO,Non-Polar Inclined,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6272,Starlink-5089,Starlink-5089,USA,USA,SpaceX,Commercial,Communications,NaN,LEO,Non-Polar Inclined,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6294,Starlink-5111,Starlink-5111,USA,USA,SpaceX,Commercial,Communications,NaN,LEO,Non-Polar Inclined,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6323,Starlink-5140,Starlink-5140,USA,USA,SpaceX,Commercial,Communications,NaN,LEO,Non-Polar Inclined,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6519,Starlink-5370,Starlink-5370,USA,USA,SpaceX,Commercial,Communications,NaN,LEO,Non-Polar Inclined,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6523,Starlink-5374,Starlink-5374,USA,USA,SpaceX,Commercial,Communications,NaN,LEO,Non-Polar Inclined,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6526,Starlink-5376,Starlink-5376,USA,USA,SpaceX,Commercial,Communications,NaN,LEO,Non-Polar Inclined,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
rows_before = clean_df.shape[0]

In [12]:
clean_df = clean_df.drop_duplicates()

In [13]:
rows_after = clean_df.shape[0]

print("=" * 50)
print("DUPLICATE REMOVAL SUMMARY")
print("=" * 50)

print(f"Rows Before Cleaning : {rows_before}")
print(f"Rows After Cleaning  : {rows_after}")
print(f"Duplicates Removed   : {rows_before - rows_after}")

==================================================
DUPLICATE REMOVAL SUMMARY
==================================================
Rows Before Cleaning : 7560
Rows After Cleaning  : 7553
Duplicates Removed   : 7

In [14]:
unnamed_columns = [col for col in clean_df.columns if "Unnamed" in col]

print("=" * 50)
print("UNNAMED COLUMNS")
print("=" * 50)

print(f"Total Unnamed Columns: {len(unnamed_columns)}")

for col in unnamed_columns:
    print(col)

==================================================
UNNAMED COLUMNS
==================================================
Total Unnamed Columns: 32
Unnamed: 28
Unnamed: 37
Unnamed: 38
Unnamed: 39
Unnamed: 40
Unnamed: 41
Unnamed: 42
Unnamed: 43
Unnamed: 44
Unnamed: 45
Unnamed: 46
Unnamed: 47
Unnamed: 48
Unnamed: 49
Unnamed: 50
Unnamed: 51
Unnamed: 52
Unnamed: 53
Unnamed: 54
Unnamed: 55
Unnamed: 56
Unnamed: 57
Unnamed: 58
Unnamed: 59
Unnamed: 60
Unnamed: 61
Unnamed: 62
Unnamed: 63
Unnamed: 64
Unnamed: 65
Unnamed: 66
Unnamed: 67

In [15]:
unnamed_columns = [col for col in clean_df.columns if "Unnamed" in col]

print(f"Total Unnamed Columns: {len(unnamed_columns)}")

for col in unnamed_columns:
    print(col)

Total Unnamed Columns: 32
Unnamed: 28
Unnamed: 37
Unnamed: 38
Unnamed: 39
Unnamed: 40
Unnamed: 41
Unnamed: 42
Unnamed: 43
Unnamed: 44
Unnamed: 45
Unnamed: 46
Unnamed: 47
Unnamed: 48
Unnamed: 49
Unnamed: 50
Unnamed: 51
Unnamed: 52
Unnamed: 53
Unnamed: 54
Unnamed: 55
Unnamed: 56
Unnamed: 57
Unnamed: 58
Unnamed: 59
Unnamed: 60
Unnamed: 61
Unnamed: 62
Unnamed: 63
Unnamed: 64
Unnamed: 65
Unnamed: 66
Unnamed: 67

In [16]:
# Find all unnamed columns
unnamed_columns = [col for col in clean_df.columns if "Unnamed" in col]

print("=" * 50)
print("UNNAMED COLUMNS")
print("=" * 50)

print(f"Total Unnamed Columns: {len(unnamed_columns)}")

for col in unnamed_columns:
    print(col)

==================================================
UNNAMED COLUMNS
==================================================
Total Unnamed Columns: 32
Unnamed: 28
Unnamed: 37
Unnamed: 38
Unnamed: 39
Unnamed: 40
Unnamed: 41
Unnamed: 42
Unnamed: 43
Unnamed: 44
Unnamed: 45
Unnamed: 46
Unnamed: 47
Unnamed: 48
Unnamed: 49
Unnamed: 50
Unnamed: 51
Unnamed: 52
Unnamed: 53
Unnamed: 54
Unnamed: 55
Unnamed: 56
Unnamed: 57
Unnamed: 58
Unnamed: 59
Unnamed: 60
Unnamed: 61
Unnamed: 62
Unnamed: 63
Unnamed: 64
Unnamed: 65
Unnamed: 66
Unnamed: 67

In [17]:
clean_df.drop(columns=unnamed_columns, inplace=True)

print("Unnamed columns removed successfully.")

Unnamed columns removed successfully.

In [18]:
print("=" * 50)
print("DATASET AFTER REMOVING UNNAMED COLUMNS")
print("=" * 50)

print(f"Rows    : {clean_df.shape[0]}")
print(f"Columns : {clean_df.shape[1]}")

==================================================
DATASET AFTER REMOVING UNNAMED COLUMNS
==================================================
Rows    : 7553
Columns : 36

In [19]:
source_columns = [col for col in clean_df.columns if str(col).startswith("Source")]

print(f"Total Source Columns: {len(source_columns)}")

for col in source_columns:
    print(col)

Total Source Columns: 8
Source Used for Orbital Data
Source
Source.1
Source.2
Source.3
Source.4
Source.5
Source.6

In [20]:
print(f"Total Unnamed Columns: {len(unnamed_columns)}")

Total Unnamed Columns: 32

In [21]:
# Remove all unnamed columns
clean_df.drop(columns=unnamed_columns, inplace=True)

print("=" * 50)
print("UNNAMED COLUMNS REMOVED")
print("=" * 50)
print(f"Columns Removed: {len(unnamed_columns)}")
print(f"Remaining Columns: {clean_df.shape[1]}")

KeyError: "['Unnamed: 28', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67'] not found in axis"

In [22]:
print(clean_df.shape)

(7553, 36)

In [23]:
clean_df.drop(
    columns=unnamed_columns,
    inplace=True,
    errors="ignore"
)

In [24]:
# Find all source columns
source_columns = [col for col in clean_df.columns if str(col).startswith("Source")]

print("=" * 50)
print("SOURCE COLUMNS")
print("=" * 50)

print(f"Total Source Columns: {len(source_columns)}")

for col in source_columns:
    print(col)

==================================================
SOURCE COLUMNS
==================================================
Total Source Columns: 8
Source Used for Orbital Data
Source
Source.1
Source.2
Source.3
Source.4
Source.5
Source.6

In [25]:
clean_df[source_columns].head()

,Source Used for Orbital Data,Source,Source.1,Source.2,Source.3,Source.4,Source.5,Source.6
0,JMSatcat/3_20,https://spaceflightnow.com/2019/12/11/indias-5...,https://www.herasys.com/,NaN,NaN,NaN,NaN,NaN
1,JMSatcat/9_23,https://www.aac-clyde.space/articles/aac-clyde...,NaN,NaN,NaN,NaN,NaN,NaN
2,JMSatcat/10_17,https://directory.eoportal.org/web/eoportal/sa...,NaN,http://www.planet4589.org/space/log/satcat.txt,NaN,NaN,NaN,NaN
3,Space50,http://spaceflightnow.com/2016/04/26/soyuz-bla...,NaN,http://space50.org/objekt.php?mot=2016-025E&ja...,NaN,NaN,NaN,NaN
4,ZARYA,http://www.absatellite.net/satellite-fleet/?sa...,NaN,http://www.zarya.info/Diaries/Launches/Launche...,http://www.absatellite.net/2010/10/13/asia-bro...,http://www.spacenews.com/article/satellite-tel...,NaN,NaN

In [26]:
source_columns = [col for col in clean_df.columns if str(col).startswith("Source")]

print(f"Total Source Columns: {len(source_columns)}")

for col in source_columns:
    print(col)

Total Source Columns: 8
Source Used for Orbital Data
Source
Source.1
Source.2
Source.3
Source.4
Source.5
Source.6

In [27]:
clean_df[source_columns].head()

,Source Used for Orbital Data,Source,Source.1,Source.2,Source.3,Source.4,Source.5,Source.6
0,JMSatcat/3_20,https://spaceflightnow.com/2019/12/11/indias-5...,https://www.herasys.com/,NaN,NaN,NaN,NaN,NaN
1,JMSatcat/9_23,https://www.aac-clyde.space/articles/aac-clyde...,NaN,NaN,NaN,NaN,NaN,NaN
2,JMSatcat/10_17,https://directory.eoportal.org/web/eoportal/sa...,NaN,http://www.planet4589.org/space/log/satcat.txt,NaN,NaN,NaN,NaN
3,Space50,http://spaceflightnow.com/2016/04/26/soyuz-bla...,NaN,http://space50.org/objekt.php?mot=2016-025E&ja...,NaN,NaN,NaN,NaN
4,ZARYA,http://www.absatellite.net/satellite-fleet/?sa...,NaN,http://www.zarya.info/Diaries/Launches/Launche...,http://www.absatellite.net/2010/10/13/asia-bro...,http://www.spacenews.com/article/satellite-tel...,NaN,NaN

In [28]:
source_columns = [col for col in clean_df.columns if str(col).startswith("Source")]

print(f"Total Source Columns: {len(source_columns)}")
print(source_columns)

Total Source Columns: 8
['Source Used for Orbital Data', 'Source', 'Source.1', 'Source.2', 'Source.3', 'Source.4', 'Source.5', 'Source.6']

In [29]:
clean_df.drop(
    columns=source_columns,
    inplace=True,
    errors="ignore"
)

print("Source columns removed successfully.")

Source columns removed successfully.

In [30]:
print(clean_df.shape)

(7553, 28)

In [31]:
clean_df.columns = clean_df.columns.str.lower()

In [32]:
column_mapping = {
    "Name of Satellite, Alternate Names": "satellite_name",
    "Current Official Name of Satellite": "official_satellite_name",
    "Country/Org of UN Registry": "un_registry_country",
    "Country of Operator/Owner": "operator_country",
    "Operator/Owner": "operator_name",
    "Users": "users",
    "Purpose": "purpose",
    "Detailed Purpose": "detailed_purpose",
    "Class of Orbit": "orbit_class",
    "Type of Orbit": "orbit_type",
    "Longitude of GEO (degrees)": "geo_longitude_deg",
    "Perigee (km)": "perigee_km",
    "Apogee (km)": "apogee_km",
    "Eccentricity": "eccentricity",
    "Inclination (degrees)": "inclination_deg",
    "Period (minutes)": "orbital_period_min",
    "Launch Mass (kg.)": "launch_mass_kg",
    "Dry Mass (kg.)": "dry_mass_kg",
    "Power (watts)": "power_watts",
    "Date of Launch": "launch_date",
    "Expected Lifetime (yrs.)": "expected_lifetime_yrs",
    "Contractor": "contractor",
    "Country of Contractor": "contractor_country",
    "Launch Site": "launch_site",
    "Launch Vehicle": "launch_vehicle"
}

In [33]:
column_mapping = {
    "Name of Satellite, Alternate Names": "satellite_name",
    "Current Official Name of Satellite": "official_satellite_name",
    "Country/Org of UN Registry": "un_registry_country",
    "Country of Operator/Owner": "operator_country",
    "Operator/Owner": "operator_name",
    "Users": "users",
    "Purpose": "purpose",
    "Detailed Purpose": "detailed_purpose",
    "Class of Orbit": "orbit_class",
    "Type of Orbit": "orbit_type",
    "Longitude of GEO (degrees)": "geo_longitude_deg",
    "Perigee (km)": "perigee_km",
    "Apogee (km)": "apogee_km",
    "Eccentricity": "eccentricity",
    "Inclination (degrees)": "inclination_deg",
    "Period (minutes)": "orbital_period_min",
    "Launch Mass (kg.)": "launch_mass_kg",
    "Dry Mass (kg.)": "dry_mass_kg",
    "Power (watts)": "power_watts",
    "Date of Launch": "launch_date",
    "Expected Lifetime (yrs.)": "expected_lifetime_yrs",
    "Contractor": "contractor",
    "Country of Contractor": "contractor_country",
    "Launch Site": "launch_site",
    "Launch Vehicle": "launch_vehicle"
}

In [34]:
clean_df.rename(columns=column_mapping, inplace=True)

print("Columns renamed successfully.")

Columns renamed successfully.

In [35]:
print("=" * 60)
print("UPDATED COLUMN NAMES")
print("=" * 60)

for i, col in enumerate(clean_df.columns, start=1):
    print(f"{i}. {col}")

============================================================
UPDATED COLUMN NAMES
============================================================
1. name of satellite, alternate names
2. current official name of satellite
3. country/org of un registry
4. country of operator/owner
5. operator/owner
6. users
7. purpose
8. detailed purpose
9. class of orbit
10. type of orbit
11. longitude of geo (degrees)
12. perigee (km)
13. apogee (km)
14. eccentricity
15. inclination (degrees)
16. period (minutes)
17. launch mass (kg.)
18. dry mass (kg.)
19. power (watts)
20. date of launch
21. expected lifetime (yrs.)
22. contractor
23. country of contractor
24. launch site
25. launch vehicle
26. cospar number
27. norad number
28. comments

In [36]:
clean_df.columns.tolist()

['name of satellite, alternate names',
 'current official name of satellite',
 'country/org of un registry',
 'country of operator/owner',
 'operator/owner',
 'users',
 'purpose',
 'detailed purpose',
 'class of orbit',
 'type of orbit',
 'longitude of geo (degrees)',
 'perigee (km)',
 'apogee (km)',
 'eccentricity',
 'inclination (degrees)',
 'period (minutes)',
 'launch mass (kg.)',
 'dry mass (kg.)',
 'power (watts)',
 'date of launch',
 'expected lifetime (yrs.)',
 'contractor',
 'country of contractor',
 'launch site',
 'launch vehicle',
 'cospar number',
 'norad number',
 'comments']

In [37]:
column_mapping = {
    "name of satellite, alternate names": "satellite_name",
    "current official name of satellite": "official_satellite_name",
    "country/org of un registry": "un_registry_country",
    "country of operator/owner": "operator_country",
    "operator/owner": "operator_name",
    "users": "users",
    "purpose": "purpose",
    "detailed purpose": "detailed_purpose",
    "class of orbit": "orbit_class",
    "type of orbit": "orbit_type",
    "longitude of geo (degrees)": "geo_longitude_deg",
    "perigee (km)": "perigee_km",
    "apogee (km)": "apogee_km",
    "eccentricity": "eccentricity",
    "inclination (degrees)": "inclination_deg",
    "period (minutes)": "orbital_period_min",
    "launch mass (kg.)": "launch_mass_kg",
    "dry mass (kg.)": "dry_mass_kg",
    "power (watts)": "power_watts",
    "date of launch": "launch_date",
    "expected lifetime (yrs.)": "expected_lifetime_yrs",
    "contractor": "contractor",
    "country of contractor": "contractor_country",
    "launch site": "launch_site",
    "launch vehicle": "launch_vehicle",
    "cospar number": "cospar_number",
    "norad number": "norad_number",
    "comments": "comments"
}

In [38]:
clean_df.rename(columns=column_mapping, inplace=True)

In [39]:
clean_df.columns.tolist()

['satellite_name',
 'official_satellite_name',
 'un_registry_country',
 'operator_country',
 'operator_name',
 'users',
 'purpose',
 'detailed_purpose',
 'orbit_class',
 'orbit_type',
 'geo_longitude_deg',
 'perigee_km',
 'apogee_km',
 'eccentricity',
 'inclination_deg',
 'orbital_period_min',
 'launch_mass_kg',
 'dry_mass_kg',
 'power_watts',
 'launch_date',
 'expected_lifetime_yrs',
 'contractor',
 'contractor_country',
 'launch_site',
 'launch_vehicle',
 'cospar_number',
 'norad_number',
 'comments']

In [40]:
missing_values = clean_df.isnull().sum()

missing_df = pd.DataFrame({
    "Column": clean_df.columns,
    "Missing Values": missing_values,
    "Missing Percentage": round((missing_values / len(clean_df)) * 100, 2)
})

missing_df = missing_df.sort_values(
    by="Missing Percentage",
    ascending=False
)

missing_df

,Column,Missing Values,Missing Percentage
power_watts,power_watts,6974,92.33
dry_mass_kg,dry_mass_kg,6786,89.85
detailed_purpose,detailed_purpose,6299,83.40
comments,comments,5468,72.40
expected_lifetime_yrs,expected_lifetime_yrs,2110,27.94
orbit_type,orbit_type,651,8.62
launch_mass_kg,launch_mass_kg,245,3.24
orbital_period_min,orbital_period_min,56,0.74
eccentricity,eccentricity,11,0.15
apogee_km,apogee_km,7,0.09
perigee_km,perigee_km,7,0.09
inclination_deg,inclination_deg,4,0.05
geo_longitude_deg,geo_longitude_deg,3,0.04
launch_date,launch_date,1,0.01
un_registry_country,un_registry_country,1,0.01
users,users,0,0.00
official_satellite_name,official_satellite_name,0,0.00
satellite_name,satellite_name,0,0.00
operator_country,operator_country,0,0.00
purpose,purpose,0,0.00
orbit_class,orbit_class,0,0.00
operator_name,operator_name,0,0.00
contractor_country,contractor_country,0,0.00
contractor,contractor,0,0.00
launch_site,launch_site,0,0.00
launch_vehicle,launch_vehicle,0,0.00
cospar_number,cospar_number,0,0.00
norad_number,norad_number,0,0.00

In [41]:
missing_df[missing_df["Missing Values"] > 0]

,Column,Missing Values,Missing Percentage
power_watts,power_watts,6974,92.33
dry_mass_kg,dry_mass_kg,6786,89.85
detailed_purpose,detailed_purpose,6299,83.40
comments,comments,5468,72.40
expected_lifetime_yrs,expected_lifetime_yrs,2110,27.94
orbit_type,orbit_type,651,8.62
launch_mass_kg,launch_mass_kg,245,3.24
orbital_period_min,orbital_period_min,56,0.74
eccentricity,eccentricity,11,0.15
apogee_km,apogee_km,7,0.09
perigee_km,perigee_km,7,0.09
inclination_deg,inclination_deg,4,0.05
geo_longitude_deg,geo_longitude_deg,3,0.04
launch_date,launch_date,1,0.01
un_registry_country,un_registry_country,1,0.01

In [42]:
print("=" * 60)
print("MISSING VALUE SUMMARY")
print("=" * 60)

print(f"Columns with Missing Values : {(missing_df['Missing Values'] > 0).sum()}")
print(f"Columns without Missing Values : {(missing_df['Missing Values'] == 0).sum()}")

============================================================
MISSING VALUE SUMMARY
============================================================
Columns with Missing Values : 15
Columns without Missing Values : 13

In [43]:
missing_df[missing_df["Missing Values"] > 0]

,Column,Missing Values,Missing Percentage
power_watts,power_watts,6974,92.33
dry_mass_kg,dry_mass_kg,6786,89.85
detailed_purpose,detailed_purpose,6299,83.40
comments,comments,5468,72.40
expected_lifetime_yrs,expected_lifetime_yrs,2110,27.94
orbit_type,orbit_type,651,8.62
launch_mass_kg,launch_mass_kg,245,3.24
orbital_period_min,orbital_period_min,56,0.74
eccentricity,eccentricity,11,0.15
apogee_km,apogee_km,7,0.09
perigee_km,perigee_km,7,0.09
inclination_deg,inclination_deg,4,0.05
geo_longitude_deg,geo_longitude_deg,3,0.04
launch_date,launch_date,1,0.01
un_registry_country,un_registry_country,1,0.01

In [44]:
columns_to_remove = [
    "power_watts",
    "dry_mass_kg",
    "detailed_purpose",
    "comments"
]

clean_df.drop(columns=columns_to_remove, inplace=True)

print("High-missing columns removed successfully.")

High-missing columns removed successfully.

In [45]:
print("=" * 50)
print("DATASET AFTER REMOVING HIGH-MISSING COLUMNS")
print("=" * 50)

print(f"Rows    : {clean_df.shape[0]}")
print(f"Columns : {clean_df.shape[1]}")

==================================================
DATASET AFTER REMOVING HIGH-MISSING COLUMNS
==================================================
Rows    : 7553
Columns : 24

In [46]:
missing_df = pd.DataFrame({
    "Column": clean_df.columns,
    "Missing Values": clean_df.isnull().sum(),
    "Missing Percentage": round(clean_df.isnull().mean() * 100, 2)
})

missing_df[missing_df["Missing Values"] > 0].sort_values(
    by="Missing Percentage",
    ascending=False
)

,Column,Missing Values,Missing Percentage
expected_lifetime_yrs,expected_lifetime_yrs,2110,27.94
orbit_type,orbit_type,651,8.62
launch_mass_kg,launch_mass_kg,245,3.24
orbital_period_min,orbital_period_min,56,0.74
eccentricity,eccentricity,11,0.15
perigee_km,perigee_km,7,0.09
apogee_km,apogee_km,7,0.09
inclination_deg,inclination_deg,4,0.05
geo_longitude_deg,geo_longitude_deg,3,0.04
un_registry_country,un_registry_country,1,0.01
launch_date,launch_date,1,0.01

In [47]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7553 entries, 0 to 7559
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   satellite_name           7553 non-null   object
 1   official_satellite_name  7553 non-null   object
 2   un_registry_country      7552 non-null   object
 3   operator_country         7553 non-null   object
 4   operator_name            7553 non-null   object
 5   users                    7553 non-null   object
 6   purpose                  7553 non-null   object
 7   orbit_class              7553 non-null   object
 8   orbit_type               6902 non-null   object
 9   geo_longitude_deg        7550 non-null   float64
 10  perigee_km               7546 non-null   float64
 11  apogee_km                7546 non-null   float64
 12  eccentricity             7542 non-null   float64
 13  inclination_deg          7549 non-null   float64
 14  orbital_period_min       7497 non-null   float64
 15  launch_mass_kg           7308 non-null   float64
 16  launch_date              7552 non-null   object
 17  expected_lifetime_yrs    5443 non-null   float64
 18  contractor               7553 non-null   object
 19  contractor_country       7553 non-null   object
 20  launch_site              7553 non-null   object
 21  launch_vehicle           7553 non-null   object
 22  cospar_number            7553 non-null   object
 23  norad_number             7553 non-null   int64
dtypes: float64(8), int64(1), object(15)
memory usage: 1.4+ MB

In [48]:
print("=" * 60)
print("CURRENT DATA TYPES")
print("=" * 60)

clean_df.info()

============================================================
CURRENT DATA TYPES
============================================================
<class 'pandas.core.frame.DataFrame'>
Index: 7553 entries, 0 to 7559
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   satellite_name           7553 non-null   object
 1   official_satellite_name  7553 non-null   object
 2   un_registry_country      7552 non-null   object
 3   operator_country         7553 non-null   object
 4   operator_name            7553 non-null   object
 5   users                    7553 non-null   object
 6   purpose                  7553 non-null   object
 7   orbit_class              7553 non-null   object
 8   orbit_type               6902 non-null   object
 9   geo_longitude_deg        7550 non-null   float64
 10  perigee_km               7546 non-null   float64
 11  apogee_km                7546 non-null   float64
 12  eccentricity             7542 non-null   float64
 13  inclination_deg          7549 non-null   float64
 14  orbital_period_min       7497 non-null   float64
 15  launch_mass_kg           7308 non-null   float64
 16  launch_date              7552 non-null   object
 17  expected_lifetime_yrs    5443 non-null   float64
 18  contractor               7553 non-null   object
 19  contractor_country       7553 non-null   object
 20  launch_site              7553 non-null   object
 21  launch_vehicle           7553 non-null   object
 22  cospar_number            7553 non-null   object
 23  norad_number             7553 non-null   int64
dtypes: float64(8), int64(1), object(15)
memory usage: 1.4+ MB

In [54]:
clean_df["launch_date"].head()

0   2019-12-11
1   2023-01-03
2   2017-06-23
3   2016-04-25
4   2014-02-06
Name: launch_date, dtype: datetime64[ns]

In [55]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7553 entries, 0 to 7559
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   satellite_name           7553 non-null   object
 1   official_satellite_name  7553 non-null   object
 2   un_registry_country      7552 non-null   object
 3   operator_country         7553 non-null   object
 4   operator_name            7553 non-null   object
 5   users                    7553 non-null   object
 6   purpose                  7553 non-null   object
 7   orbit_class              7553 non-null   object
 8   orbit_type               6902 non-null   object
 9   geo_longitude_deg        7550 non-null   float64
 10  perigee_km               7546 non-null   float64
 11  apogee_km                7546 non-null   float64
 12  eccentricity             7542 non-null   float64
 13  inclination_deg          7549 non-null   float64
 14  orbital_period_min       7497 non-null   float64
 15  launch_mass_kg           7308 non-null   float64
 16  launch_date              7550 non-null   datetime64[ns]
 17  expected_lifetime_yrs    5443 non-null   float64
 18  contractor               7553 non-null   object
 19  contractor_country       7553 non-null   object
 20  launch_site              7553 non-null   object
 21  launch_vehicle           7553 non-null   object
 22  cospar_number            7553 non-null   object
 23  norad_number             7553 non-null   int64
dtypes: datetime64[ns](1), float64(8), int64(1), object(14)
memory usage: 1.4+ MB

In [56]:
clean_df["launch_date"].head()

0   2019-12-11
1   2023-01-03
2   2017-06-23
3   2016-04-25
4   2014-02-06
Name: launch_date, dtype: datetime64[ns]

In [57]:
print("=" * 60)
print("FINAL DATASET SUMMARY")
print("=" * 60)

print(f"Rows                : {clean_df.shape[0]}")
print(f"Columns             : {clean_df.shape[1]}")
print(f"Duplicate Rows      : {clean_df.duplicated().sum()}")
print(f"Missing Values      : {clean_df.isnull().sum().sum()}")

============================================================
FINAL DATASET SUMMARY
============================================================
Rows                : 7553
Columns             : 24
Duplicate Rows      : 0
Missing Values      : 3098

In [58]:
clean_df.dtypes

satellite_name                     object
official_satellite_name            object
un_registry_country                object
operator_country                   object
operator_name                      object
users                              object
purpose                            object
orbit_class                        object
orbit_type                         object
geo_longitude_deg                 float64
perigee_km                        float64
apogee_km                         float64
eccentricity                      float64
inclination_deg                   float64
orbital_period_min                float64
launch_mass_kg                    float64
launch_date                datetime64[ns]
expected_lifetime_yrs             float64
contractor                         object
contractor_country                 object
launch_site                        object
launch_vehicle                     object
cospar_number                      object
norad_number                        int64
dtype: object

In [59]:
clean_df.head()

,satellite_name,official_satellite_name,un_registry_country,operator_country,operator_name,users,purpose,orbit_class,orbit_type,geo_longitude_deg,...,orbital_period_min,launch_mass_kg,launch_date,expected_lifetime_yrs,contractor,contractor_country,launch_site,launch_vehicle,cospar_number,norad_number
0,1HOPSAT-TD (1st-generation High Optical Perfor...,1HOPSAT-TD,NR,USA,Hera Systems,Commercial,Earth Observation,LEO,Non-Polar Inclined,0.0,...,96.08,22.0,2019-12-11,0.5,Hera Systems,USA,Satish Dhawan Space Centre,PSLV,2019-089H,44859
1,AAC AIS-Sat1 (Kelpie 1),AAC AIS-Sat1 (Kelpie 1),United Kingdom,United Kingdom,AAC Clyde Space,Commercial,Earth Observation,LEO,Sun-Synchronous,0.0,...,95.00,4.0,2023-01-03,NaN,AAC Clyde Space,Sweden/UK/USA/Netherlands,Cape Canaveral,Falcon 9,2023-001DC,55107
2,Aalto-1,Aalto-1,Finland,Finland,Aalto University,Civil,Technology Development,LEO,Sun-Synchronous,0.0,...,94.70,4.5,2017-06-23,2.0,Aalto University,Finland,Satish Dhawan Space Centre,PSLV,2017-036L,42775
3,AAt-4,AAt-4,Denmark,Denmark,University of Aalborg,Civil,Earth Observation,LEO,Sun-Synchronous,0.0,...,95.90,1.0,2016-04-25,NaN,University of Aalborg,Denmark,Guiana Space Center,Soyuz-2.1a,2016-025E,41460
4,"ABS-2 (Koreasat-8, ST-3)",ABS-2,NR,Multinational,Asia Broadcast Satellite Ltd.,Commercial,Communications,GEO,NaN,75.0,...,1436.03,6330.0,2014-02-06,15.0,Space Systems/Loral,USA,Guiana Space Center,Ariane 5 ECA,2014-006A,39508

In [60]:
output_path = "../data/processed/satellites_cleaned.csv"

clean_df.to_csv(output_path, index=False)

print(f"Dataset saved successfully to:\n{output_path}")

Dataset saved successfully to:
../data/processed/satellites_cleaned.csv

In [61]:
verification_df = pd.read_csv(output_path)

print(verification_df.shape)
verification_df.head()

(7553, 24)

,satellite_name,official_satellite_name,un_registry_country,operator_country,operator_name,users,purpose,orbit_class,orbit_type,geo_longitude_deg,...,orbital_period_min,launch_mass_kg,launch_date,expected_lifetime_yrs,contractor,contractor_country,launch_site,launch_vehicle,cospar_number,norad_number
0,1HOPSAT-TD (1st-generation High Optical Perfor...,1HOPSAT-TD,NR,USA,Hera Systems,Commercial,Earth Observation,LEO,Non-Polar Inclined,0.0,...,96.08,22.0,2019-12-11,0.5,Hera Systems,USA,Satish Dhawan Space Centre,PSLV,2019-089H,44859
1,AAC AIS-Sat1 (Kelpie 1),AAC AIS-Sat1 (Kelpie 1),United Kingdom,United Kingdom,AAC Clyde Space,Commercial,Earth Observation,LEO,Sun-Synchronous,0.0,...,95.00,4.0,2023-01-03,NaN,AAC Clyde Space,Sweden/UK/USA/Netherlands,Cape Canaveral,Falcon 9,2023-001DC,55107
2,Aalto-1,Aalto-1,Finland,Finland,Aalto University,Civil,Technology Development,LEO,Sun-Synchronous,0.0,...,94.70,4.5,2017-06-23,2.0,Aalto University,Finland,Satish Dhawan Space Centre,PSLV,2017-036L,42775
3,AAt-4,AAt-4,Denmark,Denmark,University of Aalborg,Civil,Earth Observation,LEO,Sun-Synchronous,0.0,...,95.90,1.0,2016-04-25,NaN,University of Aalborg,Denmark,Guiana Space Center,Soyuz-2.1a,2016-025E,41460
4,"ABS-2 (Koreasat-8, ST-3)",ABS-2,NR,Multinational,Asia Broadcast Satellite Ltd.,Commercial,Communications,GEO,NaN,75.0,...,1436.03,6330.0,2014-02-06,15.0,Space Systems/Loral,USA,Guiana Space Center,Ariane 5 ECA,2014-006A,39508